updateTime: 2500
log_channel: "1304434908587888796"
web: "https://www.staminamc.fun"
title: "StaminaMC"
enabled: false
timestamp: true
footer: true
footer_icon: true
list:
  java:
    ip: "play.staminamc.fun"
    port: 25565
    address: play.staminamc.fun
    title: á´Šá´€á´ á´€
    support: 1.8 - 1.20.4
    isBedrock: false
present:
  host: "Êœá´êœ±á´›:"
  status: "êœ±á´›á´€á´›á´œêœ±:"
  online: "á´É´ÊŸÉªÉ´á´‡:"
  version: "á´ á´‡Ê€êœ±Éªá´É´:"
  timer: "Updating ever %s"
  state:
    online: ğŸŸ¢ á´É´ÊŸÉªÉ´á´‡
    offline: ğŸ”´ á´êœ°êœ°ÊŸÉªÉ´á´‡
    error: ğŸŸ¡ á´œÉ´á´‹É´á´á´¡É´
