enabled: false
logging: false

settings:
  updateTime: 30000
  log_channel: "1304490899832832010"
  title: "MaxGaming"
  timestamp: true
  footer: true
  web: "https://panel.maxgaming.bg"
  footer_icon: true

present:
  host: "Êœá´êœ±á´›:"
  status: "êœ±á´›á´€á´›á´œêœ±:"
  timer: "á´œá´˜á´…á´€á´›ÉªÉ´É¢ á´‡á´ á´‡Ê€Ê %s"
  inline: false
  state:
    online: ğŸŸ¢ á´É´ÊŸÉªÉ´á´‡
    offline: ğŸ”´ á´êœ°êœ°ÊŸÉªÉ´á´‡
    error: ğŸŸ¡ á´œÉ´á´‹É´á´á´¡É´

list:
  Panel:
    url: "https://panel.maxgaming.bg"
    expect: 200
    enabled: false
    web: false
  Gaming1:
    url: "https://g1.maxgaming.bg:25589"
    expect: 401
    enabled: false
    web: false